name: GitOps actions
on: workflow_dispatch
env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: gitops-ecr
  EKS_CLUSTER: Gitops-eks

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      # Setup Java 11 to be default (SonarScanner requirement as of 5.x)
      - name: Set Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Setup SonarQube
  BUILD_AND_PUBLISH:   
   needs: Testing
   runs-on: ubuntu-latest
   env:
     AWS_REGION: eu-north-1
     ECR_REPOSITORY: gitops-ecr
   steps:
     - name: Code checkout
       uses: actions/checkout@v4

     - name: Build & Upload image to ECR
       uses: appleboy/docker-ecr-action@master
       with:
         access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
         secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         registry: ${{ secrets.REGISTRY }}
         repo: ${{ env.ECR_REPOSITORY }}
         region: ${{ env.AWS_REGION }}
         tags: latest,${{ github.run_number }}
         daemon_off: false
         dockerfile: ./Dockerfile
         context: ./


